version: '3'

x-environment: &mysql_environments
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bennu

services:
  nginx:
    image: bitnami/nginx:latest
    # platform: linux/amd64
    container_name: nginx
    restart: always
    ports:
      - 8443:8443
    volumes:
      - ./manifests/configs:/opt/bitnami/nginx/conf/server_blocks
      - staticfiles:/usr/share/nginx/html
    depends_on:
      - gunicorn

  gunicorn:
    image: ghcr.io/hwakabh/bennu-official:latest
    # platform: linux/amd64
    environment:
      <<: *mysql_environments
      MYSQL_USER: root
      MYSQL_HOSTNAME: mysql
    container_name: gunicorn
    restart: always
    ports:
      - 8000:8000
    volumes:
      - staticfiles:/workspace/assets
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy

  mysql:
    image: bitnami/mysql:latest
    # platform: linux/amd64
    environment:
      <<: *mysql_environments
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    tty: true
    healthcheck:
      test: "mysqladmin ping || exit 1"
      interval: 3s
      retries: 3
    volumes:
      - mysql-data:/opt/bitnami/mysql/data

  minio:
    image: bitnami/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: bennu:public
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-data:/bitnami/minio/data
    healthcheck:
      test: "mc ping local --count 1 || exit 1"
      interval: 3s
      retries: 3
    deploy:
      restart_policy:
        condition: on-failure

volumes:
  staticfiles:
  mysql-data:
  minio-data:
