version: '3'

x-environment: &mysql_environments
  MYSQL_HOSTNAME: mysql
  MYSQL_ROOT_PASSWORD: root
  MYSQL_DATABASE: bennu

services:
  django:
    image: ghcr.io/hwakabh/bennu-official:latest
    # platform: linux/amd64
    environment:
      <<: *mysql_environments
      MYSQL_USER: root
    container_name: django
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mysql

  mysql:
    image: bitnami/mysql:latest
    # platform: linux/amd64
    environment:
      <<: *mysql_environments
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    tty: true
