---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bennu
  name: django
  namespace: bennuhp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bennu
  strategy: {}
  template:
    metadata:
      labels:
        app: bennu
    spec:
      initContainers:
      # - image: ghcr.io/hwakabh/bennu-official:latest
      #   name: collectstatic
      #   command:
      #   - /cnb/process/collectstatic
      #   envFrom:
      #     - secretRef:
      #         name: app-secret
      - image: ghcr.io/hwakabh/bennu-official:latest
        name: migrate
        command:
        - /cnb/process/migrate
        envFrom:
          - secretRef:
              name: app-secret
      - image: ghcr.io/hwakabh/bennu-official:latest
        name: loaddata
        command:
        - /cnb/process/seeds
        envFrom:
          - secretRef:
              name: app-secret
      containers:
      # TODO: need to replace SHA instead of latest tag
      - image: ghcr.io/hwakabh/bennu-official:latest
        imagePullPolicy: Always
        name: django
        envFrom:
          - secretRef:
              name: app-secret
        volumeMounts:
        - mountPath: /workspace/assets
          name: static
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 60
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
      volumes:
      - name: static
        persistentVolumeClaim:
          claimName: staticfiles
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bennu
  name: django
  namespace: bennuhp
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: bennu
  type: ClusterIP
