---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bennu-app
  namespace: bennuhp
  annotations:
    cert-manager.io/issuer: "letsencrypt"
spec:
  tls:
    - hosts:
        - bennu-official.page
      # cert-manager automatically generate secret
      secretName: tls-cert
  ingressClassName: "nginx"
  rules:
  - host: bennu-official.page
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: django
            port:
              number: 8000
      - pathType: Prefix
        path: "/assets"
        backend:
          service:
            name: nginx
            port:
              number: 80
