apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bennuhp
resources:
  - ./namespace.yaml
  - ./minio.yaml
  - ./sealed-secrets.yaml
  - ./mysql.yaml
  - ./django.yaml
  - ./nginx.yaml
configMapGenerator:
  - name: nginx-etc
    files:
      - ./configs/nginx.conf
