apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bennuhp
resources:
  # - ./controllers/ingress-nginx-controller.yaml
  # - ./controllers/sealed-secret-controller.yaml
  - ./namespace.yaml
  - ./sealed-secrets.yaml
  - ./nfs-server.yaml
  - ./staticfiles.yaml
  - ./mysql.yaml
  - ./django.yaml
  - ./nginx.yaml
  - ./ingress.yaml
configMapGenerator:
  - name: nginx-etc
    files:
      - ./configs/nginx.conf
# replicas:
#   - name: ingress-nginx-controller
#     count: 3
