---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bennu
  name: minio
  namespace: bennuhp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bennu
  serviceName: minio
  template:
    metadata:
      labels:
        app: bennu
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        imagePullPolicy: Always
        args:
          - server
          - /export
          - --console-address
          - :9001
        envFrom:
          - secretRef:
              name: minio-secret
        volumeMounts:
        - mountPath: /export
          name: minio-data
        ports:
        - name: minio
          containerPort: 9000
        - name: minio-ui
          containerPort: 9001
  volumeClaimTemplates:
  - metadata:
      name: minio-data
      namespace: bennu
      labels:
        app: bennu
    spec:
      storageClassName: standard-rwo
      accessModes:
      - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: bennuhp
  labels:
    app: bennu
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: minio
  - port: 9001
    protocol: TCP
    targetPort: 9001
    name: minio-ui
  selector:
    app: bennu
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: minio-front
  namespace: bennuhp
  labels:
    app: bennu
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
    name: minio
  - port: 9001
    protocol: TCP
    targetPort: 9001
    name: minio-ui
  selector:
    app: bennu
  type: LoadBalancer
  loadBalancerIP: 34.121.252.242
