---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticfiles
  namespace: bennuhp
  labels:
    app: bennu
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.bennuhp.svc.cluster.local
    path: "/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticfiles
  namespace: bennuhp
  labels:
    app: bennu
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
