# Shared between nginx/django for staticfiles
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: bennu
  name: staticfiles
  namespace: bennuhp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard-rwo  # GKE option
  volumeMode: Filesystem
