name: Build App Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        # https://github.com/docker/login-action#github-container-registry

      # TODO: TBD
      # - name: Unit Test with Django buildin
      # - name: Security Test with Trivy

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.0.0
        # https://github.com/buildpacks/github-actions#setup-pack-cli-action

      - name: Build image locally
        run: |
          pack build ghcr.io/hwakabh/bennu-official:latest \
            --builder paketobuildpacks/builder-jammy-full \
            --buildpack paketo-buildpacks/python \
            --path . \
            --env "$(cat .python-version)" \

      # TODO: TBD
      # - name: Sanity Check with /healthz served by gunicorn within container image
