name: Build App Image

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:

jobs:
  build_and_ship:
    name: Build & Ship OCI image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PUSH_TOKEN }}

      # References:
      # - https://github.com/mamezou-tech/buildpacks-action
      # - https://github.com/marketplace/actions/buildpacks-action
      - name: Invoke buildpacks-action
        uses: mamezou-tech/buildpacks-action@master
        with:
          image: 'ghcr.io/hwakabh/bennu-official/django'
          tag: 'latest'
          builder: 'paketobuildpacks/builder:full'
          # buildpacks: 'paketo-buildpacks/python'
          # TODO: should be fetched from .python-version
          env: 'BP_CPYTHON_VERSION=3.11.5'
          publish: true
