name: Build

on:
  push:
    branches:
      - '**'
      - '!main'
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: 'pip'
          # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#using-the-python-version-file-input

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Unit Test with Django buildin
        run: |
          python manage.py test --debug-mode -v 2
